#!/usr/bin/python

# ######################################################################
# Imports
# ######################################################################

import rostest

# System-builtins
import argparse
import sys

# Local
from testutils import TestQueryJobStore
from test_sat_queryjob_scheduler import (
    test_sat_schedule_single_task_single_location,
    test_sat_schedule_single_task_multiple_locations,
    test_sat_schedule_multiple_tasks_multiple_locations
)

# ######################################################################
# Module level constants
# ######################################################################

PKG = "sat_schedule_solver"


# ######################################################################
# Main
# ######################################################################

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("--testcase_id", type=int,
                        help="ID of the test case.")
    args, unknown = parser.parse_known_args()

    if args.testcase_id == 0:
        NAME = "test_sat_schedule_single_task_single_location"
        setattr(TestQueryJobStore,
                NAME,
                test_sat_schedule_single_task_single_location)
        rostest.run(PKG, NAME, TestQueryJobStore)
    elif args.testcase_id == 1:
        NAME = "test_sat_schedule_single_task_multiple_locations"
        setattr(TestQueryJobStore,
                NAME,
                test_sat_schedule_single_task_multiple_locations)
        rostest.run(PKG, NAME, TestQueryJobStore)
    elif args.testcase_id == 2:
        NAME = "test_sat_schedule_multiple_tasks_multiple_locations"
        setattr(TestQueryJobStore,
                NAME,
                test_sat_schedule_multiple_tasks_multiple_locations)
        rostest.run(PKG, NAME, TestQueryJobStore)
    else:
        print >> sys.stderr, "unknown testcase_id: {0}".format(
            args.testcase_id)
        sys.exit(1)
